- web/components/editForm/EditForm.tsx
- web/components/panelDetails/PanelDetails.tsx
- web/components/symbolEditor/SymbolEditor.tsx
- web/components/symbolEditor/index.ts
- web/components/symbolEditor/styles.ts
- web/components/symbolEditor/world-objects/ConnectorLabel.ts
- web/components/symbolEditor/world-objects/Info.ts
- web/pages/edit/index.page.tsx
- web/pages/edit/styles.ts
> feat: Integrate metadata editor in the Symbol Editor

- web/components/editForm/EditForm.tsx
- web/components/editForm/styles.ts
- web/components/panelDetails/PanelDetails.tsx
> chore: validation for inputs

- web/components/editForm/EditForm.tsx
- web/components/panelDetails/PanelDetails.tsx
- web/components/preview/Preview.tsx
- web/components/symbolEditor/World.ts
- web/components/symbolEditor/event.ts
- web/components/symbolEditor/models/EditorCommand.ts
- web/components/symbolEditor/models/EditorEvent.ts
- web/components/symbolEditor/models/EditorSettings.ts
- web/components/symbolEditor/models/SymbolData.ts
- web/components/symbolEditor/utils/context2d.ts
- web/components/symbolEditor/world-objects/Connector.ts
- web/components/symbolEditor/world-objects/ConnectorLabel.ts
- web/components/symbolEditor/world-objects/ConnectorLayer.ts
- web/components/symbolEditor/world-objects/FrameBorder.ts
- web/components/symbolEditor/world-objects/Info.ts
- web/pages/edit/index.page.tsx
- web/types/index.ts
Add a symbol update command that updates all props at the same time.
> feat: symbol update command

- web/components/editForm/EditForm.tsx
- web/components/editForm/styles.ts
- web/components/panelDetails/PanelDetails.tsx
- web/package-lock.json
- web/package.json
- web/pages/edit/index.page.tsx
> chore: click & scroll

- web/components/editForm/EditForm.tsx
- web/components/editForm/styles.ts
- web/components/panelDetails/PanelDetails.tsx
- web/components/panelDetails/styles.ts
> fix: Position of "Save" | "Cancel" buttons in form

- web/components/symbolEditor/World.ts
- web/components/symbolEditor/utils/strings.ts
> chore: ID | Name - unique

- web/components/preview/Preview.tsx
> chore: remove connectors name from presentation

- web/pages/edit/index.page.tsx
- web/pages/edit/styles.ts
> chore: Implement search on edit page

- web/components/editForm/styles.ts
- web/components/panelDetails/PanelDetails.tsx
- web/components/panelDetails/styles.ts
- web/components/zoomButtons/styles.ts
- web/pages/edit/index.page.tsx
- web/pages/edit/styles.ts
- web/types/index.ts
> feat: Filter for status + edit panel to right

- web/api/API.ts
- web/store/Symbols/SymbolsAction.tsx
> fix: updateSymbol API

- web/pages/edit/index.page.tsx
> fix: popup when you browse the page

- web/components/iconButton/IconButton.tsx
- web/components/iconButton/icons/Face3d.tsx
- web/components/iconButton/icons/FloppyDisk.tsx
- web/components/iconButton/icons/LensMinus.tsx
- web/components/iconButton/icons/LensPlus.tsx
- web/components/iconButton/icons/Wrench.tsx
- web/components/iconButton/icons/Xmark.tsx
- web/components/iconButton/icons/ZoomOut.tsx
- web/components/iconButton/icons/index.ts
- web/components/iconButton/styles.ts
- web/components/list/List.tsx
- web/pages/edit/index.page.tsx
- web/pages/edit/styles.ts
- web/styles/Themes.js
- web/svg/cat.svg
> chore: quick save & cancel button

- web/components/panelDetails/PanelDetails.tsx
- web/components/symbolEditor/World.ts
- web/components/symbolEditor/models/SymbolData.ts
- web/pages/edit/index.page.tsx
- web/store/Symbols/SymbolsAction.tsx
> fix: symbol picking

- web/pages/_app.page.tsx
- web/pages/contribution/contribution.md
> chore: update contribution *md

- web/components/signButton/SignButton.tsx
> fix: login problem in fullscreen mode

- web/pages/manage/index.page.tsx
> chore: Implement selected connector scroll

- web/pages/manage/index.page.tsx
- web/store/Symbols/SymbolsAction.tsx
> fix: duplicate when saving in Draft | fix Updated message

- web/pages/manage/index.page.tsx
> chore: make filter statuses static

- web/components/editForm/EditForm.tsx
- web/components/editForm/styles.ts
- web/components/header/Header.tsx
- web/components/header/styles.ts
- web/components/iconButton/IconButton.tsx
- web/components/iconButton/icons/RotateTR.tsx
- web/components/iconButton/icons/index.ts
- web/components/list/List.tsx
- web/components/signButton/SignButton.tsx
- web/components/signButton/styles.ts
- web/components/symbolEditor/event.ts
- web/pages/manage/index.page.tsx
- web/styles/styles.ts
> chore: visual upgrade v.2

- web/pages/manage/index.page.tsx
> fix: click drag&drop area

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
- package/README.md
- package/package-lock.json
- package/package.json
- readme.md
- web/README.md
- web/package-lock.json
> chore: more documentation

- .github/workflows/web-dev-release.yml
- .github/workflows/web.yml
- .releaserc
- package-lock.json
- package.json
- package/README.md
- radixconfig.yaml
- web/README.md
> refactor: Semantic Release
